name: Selenium Tests with Maven (Chrome Only)

on:
  push:
    branches:
      - main  # Cambia a tu rama principal (main, master, etc.)
  pull_request:
    branches:
      - main  # Cambia a tu rama principal

jobs:
  test:
    runs-on: ubuntu-latest  # Usa el último Ubuntu para compatibilidad

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configura Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # Usa Temurin (Adoptium) como distribución de Java

      # Paso 3: Instala Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Paso 4: Ejecuta las pruebas con Maven
      - name: Run tests with Maven
        run: mvn test -Dbrowser=chrome  # Ejecuta pruebas solo en Chrome