name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'  # Otras opciones: 'adoptopenjdk', 'zulu', etc.

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: mvn clean test
