name: Run Selenium Tests with Maven

on:
  push:
    branches:
      - main  # Cambia esto a la rama que desees (por ejemplo, "main" o "master")
  pull_request:
    branches:
      - main  # Cambia esto a la rama que desees

jobs:
  test:
    runs-on: ubuntu-latest  # Usa un entorno Ubuntu para ejecutar las pruebas

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configura Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # Usa Temurin (Adoptium) como distribución de Java

      # Paso 3: Ejecuta las pruebas con Maven
      - name: Run tests with Maven
        run: mvn test

      # Paso 4: Sube los resultados de las pruebas (opcional)
      - name: Upload test results
        if: always()  # Sube los resultados incluso si las pruebas fallan
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports  # Cambia esto si tus resultados están en otra carpeta