name: Run TestNG Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      - name: selenium/standalone-chrome
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # También puedes probar con 'zulu' si temurin falla
          java-version: '21' # Asegúrate de que sea 21

      - name: Build and Test
        run: mvn clean test

      - name: Run tests
        run: mvn test
        env:
          DISPLAY: :99.0
